spring:
  application:
    name: promptvault
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Groq API (gratis - https://console.groq.com)
groq:
  api:
    key: ${GROQ_API_KEY:}